scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'exporter'
    static_configs:
      - targets: [ 'apihandler:9999' ]